// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oopresehaaqofebhfcdp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9vcHJlc2VoYWFxb2ZlYmhmY2RwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3NzY3ODAsImV4cCI6MjA3MzM1Mjc4MH0.Ixbzu1hBQWMxor8vHB1WqHC3WXiY52NkQw-7a8-HC8I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});